apiVersion: v1
kind: BuildConfig
metadata:
  name: tpfrankdemo-pipeline
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        pipeline {
          agent { label "maven" }
          stages {
            stage("Clone Source") {
              steps {
                checkout([$class: 'GitSCM',
                  branches: [[name: '*/master']],
                  extensions: [
                    [$class: 'RelativeTargetDirectory', relativeTargetDir: 'tpfrankdemo']
                  ],
                    userRemoteConfigs: [[url: 'https://github.com/fcallaly/spring-boot-lambda-demo.git']]
                ])
              }
            }

            stage("Build JAR") {
              steps {
                dir('tpfrankdemo') {
                  sh 'mvn -Dboot clean package'
                }
              }
            }

            stage("Create Build") {
              steps {
                dir('tpfrankdemo') {
                  sh 'oc new-build --strategy docker --binary --name tpfrankdemo || echo "Build already exists"'
                }
              }
            }

            stage("Build Image") {
              steps {
                dir('tpfrankdemo') {
                  sh 'oc start-build tpfrankdemo --from-dir . --follow'
                }
              }
            }
          }
        }
      type: JenkinsPipeline
      triggers: []
