AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - com.frankc.training::lambda-demo
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  LambdaDemoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.frankc.training.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/lambda-demo-0.0.1-SNAPSHOT-lambda-package.zip
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  LambdaDemoApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: LambdaDemoApi
